export declare const sliderDriverFactory: ({ element, eventTrigger }: {
    element: any;
    eventTrigger: any;
}) => {
    exists: () => boolean;
    value: () => number;
    min: () => number;
    max: () => number;
    vertical: () => boolean;
    thumb: () => any;
    tooltip: () => any;
    ticks: () => any;
    track: () => any;
    rtl: () => boolean;
    root: () => any;
    mouseMove(value: any): void;
    mouseDown(): void;
    mouseUp(): void;
    focus(): void;
    blur(): void;
    arrowLeft(): void;
    arrowRight(): void;
    arrowUp(): void;
    arrowDown(): void;
    pageUp(): void;
    pageDown(): void;
    home(): void;
    end(): void;
    stubTrackBoundingRect(rect?: any): void;
    stubRootBoundingRect(rect?: any): void;
    getTrackBoundingRect(): any;
    getRootBoundingRect(): any;
    getThumbSize(): any;
    getOffsetByValue(value: any): number;
    change(value?: number): void;
    hoverThumb(): void;
    unhoverThumb(): void;
    dragThumb(offset: any): void;
    thumbTooltipValue(): any;
    clickTick(tickIdx: any): void;
    clickSlider(value: any): void;
    forceUpdate(): void;
};
